services:
  apache:
    image: httpd:2.4
    restart: unless-stopped
    volumes:
      - ./docs:/usr/local/apache2/htdocs/
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 2019:80
    networks:
      - npmplus_default

networks:
  npmplus_default:
    external: true
